# Generated by Django 5.2.7 on 2025-10-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField()),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
