# Generated by Django 5.1.1 on 2025-10-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_name',
            field=models.CharField(max_length=10),
        ),
    ]
